# Generated by Django 4.2.11 on 2025-03-06 07:50

import autoslug.fields
import core_apps.products.fields
import core_apps.products.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attribute_value", models.CharField(max_length=100)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_value",
                        to="products.attribute",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Format: required, max-length=100",
                        max_length=100,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=core_apps.products.models.get_product_slug,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Format: optional",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_digital",
                    models.BooleanField(
                        default=False,
                        help_text="Format: true=Digital Product, false=Physical Product",
                        verbose_name="Digital Product",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductLine",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Price",
                    ),
                ),
                ("sku", models.CharField(max_length=10)),
                ("stock_qty", models.IntegerField()),
                ("weight", models.FloatField()),
                ("is_active", models.BooleanField(default=False)),
                ("order", core_apps.products.fields.OrderField(blank=True)),
            ],
            options={
                "verbose_name": "Product Line",
                "verbose_name_plural": "Product Lines",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductLineAttributeValue",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribute_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_attribute_value_av",
                        to="products.attributevalue",
                    ),
                ),
                (
                    "product_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_attribute_value_pl",
                        to="products.productline",
                    ),
                ),
            ],
            options={
                "unique_together": {("attribute_value", "product_line")},
            },
        ),
        migrations.AddField(
            model_name="productline",
            name="attribute_value",
            field=models.ManyToManyField(
                related_name="product_line_attribute_value",
                through="products.ProductLineAttributeValue",
                to="products.attributevalue",
                verbose_name="Attribute Values",
            ),
        ),
        migrations.AddField(
            model_name="productline",
            name="product",
            field=models.ForeignKey(
                help_text="Format: required, references Product model",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_lines",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alternative_text",
                    models.CharField(
                        help_text="Format: required, max-length=100",
                        max_length=100,
                        verbose_name="Alternative Text",
                    ),
                ),
                (
                    "url",
                    models.ImageField(
                        default="product_images/default.jpg",
                        help_text="Format: required, default image provided",
                        upload_to="product_images/",
                        verbose_name="Image URL",
                    ),
                ),
                (
                    "order",
                    core_apps.products.fields.OrderField(
                        blank=True,
                        help_text="Format: auto-assigned if not specified",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "product_line",
                    models.ForeignKey(
                        help_text="Format: required, references ProductLine",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_images",
                        to="products.productline",
                        verbose_name="Product Line",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribute_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_value_av",
                        to="products.attributevalue",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_value_pl",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("attribute_value", "product")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="attribute_values",
            field=models.ManyToManyField(
                related_name="product_attr_value",
                through="products.ProductAttributeValue",
                to="products.attributevalue",
                verbose_name="Product Attributes",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=mptt.fields.TreeForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="categories.category",
                verbose_name="Category",
            ),
        ),
    ]
