# Generated by Django 4.2.11 on 2025-03-05 07:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Format: required, max-length=100",
                        max_length=100,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Format: required, letters, numbers, underscore, or hyphens",
                        max_length=255,
                        verbose_name="Product Safe URL",
                    ),
                ),
                (
                    "pid",
                    models.CharField(
                        help_text="Format: required, unique, max-length=10",
                        max_length=10,
                        unique=True,
                        verbose_name="Product ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Format: optional",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_digital",
                    models.BooleanField(
                        default=False,
                        help_text="Format: true=Digital Product, false=Physical Product",
                        verbose_name="Digital Product",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Format: true=product visible",
                        verbose_name="Product Visibility",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Format: required, reference to Category",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="categories.category",
                        verbose_name="Product Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
    ]
