# Generated by Django 4.2.11 on 2025-03-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pid",
        ),
    ]
