# Generated by Django 4.2.11 on 2025-03-05 08:08

import autoslug.fields
import core_apps.products.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_pid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                populate_from=core_apps.products.models.get_product_slug,
                unique=True,
            ),
        ),
    ]
