services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: nexuscommerce_api
    container_name: nexuscommerce_api
    volumes:
      - .:/app:z
      - ./staticfiles:/app/staticfiles
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./.envs/.env.local
    depends_on:
      - postgres
      - mailpit
      - redis
    command: /start
    networks:
      - nexuscommerce_nw

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    image: nexuscommerce_postgres
    container_name: nexuscommerce_postgres
    ports:
      - "5432:5432"
    volumes:
      - nexuscommerce_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - nexuscommerce_nw 
  
  mailpit:
    image: docker.io/axllent/mailpit:v1.22
    container_name: nexuscommerce_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:  
      - nexuscommerce_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1  
    networks:
      - nexuscommerce_nw

  redis:
    image: redis:7.0-alpine3.19
    command: redis-server --appendonly yes
    container_name: nexuscommerce_redis
    volumes:
      - nexuscommerce_redis_data:/data
    networks:
      - nexuscommerce_nw

  celeryworker:
    <<: *api
    image: nexuscommerce_celeryworker
    container_name: nexuscommerce_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *api
    image: nexuscommerce_celerybeat
    container_name: nexuscommerce_celerybeat
    command: /start-celerybeat

  flower:
    <<: *api
    image: nexuscommerce_flower
    container_name: nexuscommerce_flower
    ports:
      - "5555:5555"
    command: /start-flower

  nginx:
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    restart: always
    container_name: nexuscommerce_nginx
    ports:
      - "8080:80"
    volumes:
      - ./staticfiles:/app/staticfiles
      - logs_store:/var/log/nginx
    depends_on:
      - api
    networks:
      - nexuscommerce_nw

networks:
  nexuscommerce_nw:
    

volumes:
  nexuscommerce_postgres_data: {}
  nexuscommerce_mailpit_data: {}
  nexuscommerce_redis_data: {}
  logs_store: {}