# Generated by Django 4.2.11 on 2025-02-28 07:59

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="billing_city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="billing_country",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="shipping_address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="shipping_city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="shipping_country",
        ),
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(
                default="Accra", max_length=180, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="GH", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+23324874633",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
