# Generated by Django 4.2.11 on 2025-02-28 08:49

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_profile_billing_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter phone number in international format (e.g., +233123456789)",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
